// LOCALHOST ###

// 63c32429f6611ecb7cfe5350 - Jared
// 63c32468f6611ecb7cfe5351 - Chloee
// 63c32497f6611ecb7cfe5352 - Cole

// Get ALL contacts on rest server
GET http://localhost:8080/contacts
### Get just Jareds contact on rest server
GET http://localhost:8080/contacts/63c32429f6611ecb7cfe5350
### Get just Chloees contact on normal server
GET http://localhost:3000/contacts/63c32468f6611ecb7cfe5351
### get ALL contacts on normal server
GET http://localhost:3000/contacts

### Create contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{

  "firstName": "Daniel",
  "lastName": "Larusso",
  "email": "karatekid@gmail.com",
  "favoriteColor": "yellow",
  "birthday": "1/1/1999"
  
}

### PUT contact
PUT http://localhost:3000/contacts/63c32429f6611ecb7cfe5350 HTTP/1.1
content-type: application/json

{

"firstName":"Jared",
"lastName":"Vance",
"email":"jared@gmail.com",
"favoriteColor":"green",
"birthday":"03/26/2000"

}
### DELETE contact
DELETE http://localhost:3000/contacts/63cc62de75048f8ecc0ea6b2 HTTP/1.1

### GET ALL
GET https://vance-cse-341.onrender.com/contacts HTTP/1.1

### GET ONE
GET https://vance-cse-341.onrender.com/contacts/63c32468f6611ecb7cfe5351 HTTP/1.1

### CREATE ONE
POST https://vance-cse-341.onrender.com/contacts HTTP/1.1
content-type: application/json

{

  "firstName": "Daniel",
  "lastName": "Larusso",
  "email": "karatekid@gmail.com",
  "favoriteColor": "yellow",
  "birthday": "1/1/1999"

}

### UPDATE ONE

PUT https://vance-cse-341.onrender.com/contacts/63c32429f6611ecb7cfe5350 HTTP/1.1
content-type: application/json

{

"firstName":"Jared",
"lastName":"Vance",
"email":"jared@gmail.com",
"favoriteColor":"blue",
"birthday":"03/26/2000"

}

###DElETE ONE

DELETE https://vance-cse-341.onrender.com/contacts/63d47747fa421b86b57100dc HTTP/1.1
